# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://swvpn.github.io
title: 小火箭Shadowrocket官网
email: bcins4691@gmail.com 
author: shadow rocket
description: > # "Write an awesome description for your new site here. 
  小火箭官方平台，shadowRocket 下载教程，使用教程，最新节点推荐
copyright: 'Copyright &copy; 2020 shadow rocket. All Rights Reserved.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/offical_clash
  - title: github
    url: https://github.com/Shadowrocket